export const seedUsers = [
  {
    name: 'Admin Master',
    email: 'admin@schedulo.com',
    password: 'password123',
    phone: '+1-555-0100',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250',
    isActive: true,
  },
  {
    name: 'Dr. Evelyn Vance',
    email: 'staff.vance@schedulo.com',
    password: 'password123',
    phone: '+1-555-0101',
    role: 'staff',
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=250',
    isActive: true,
  },
  {
    name: 'Marcus Holloway',
    email: 'staff.marcus@schedulo.com',
    password: 'password123',
    phone: '+1-555-0102',
    role: 'staff',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=250',
    isActive: true,
  },
  {
    name: 'Sophia Chen',
    email: 'staff.sophia@schedulo.com',
    password: 'password123',
    phone: '+1-555-0103',
    role: 'staff',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250',
    isActive: true,
  },
  {
    name: 'Alice Johnson',
    email: 'user.alice@schedulo.com',
    password: 'password123',
    phone: '+1-555-0201',
    role: 'user',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=250',
    isActive: true,
  },
  {
    name: 'Bob Smith',
    email: 'user.bob@schedulo.com',
    password: 'password123',
    phone: '+1-555-0202',
    role: 'user',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=250',
    isActive: true,
  },
  {
    name: 'Catherine Miller',
    email: 'user.catherine@schedulo.com',
    password: 'password123',
    phone: '+1-555-0203',
    role: 'user',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=250',
    isActive: true,
  },
  {
    name: 'David Taylor',
    email: 'user.david@schedulo.com',
    password: 'password123',
    phone: '+1-555-0204',
    role: 'user',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=250',
    isActive: true,
  },
  {
    name: 'Emma Watson',
    email: 'user.emma@schedulo.com',
    password: 'password123',
    phone: '+1-555-0205',
    role: 'user',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=250',
    isActive: true,
  },
  {
    name: 'Frank Ocean',
    email: 'user.frank@schedulo.com',
    password: 'password123',
    phone: '+1-555-0206',
    role: 'user',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=250',
    isActive: true,
  },
];

export const seedServices = [
  {
    name: 'General Health Consultation',
    description: 'Comprehensive annual physical assessment, vital sign inspection, and health screening.',
    duration: 30,
    category: 'Medical',
    price: 120,
    isActive: true,
  },
  {
    name: 'Specialist Dental Cleaning & Scaling',
    description: 'Deep dental plaque removal, fluoride treatment, and oral hygiene checkup.',
    duration: 45,
    category: 'Dental',
    price: 180,
    isActive: true,
  },
  {
    name: 'Executive Tech Strategy Advisory',
    description: '1-on-1 enterprise architecture assessment, cloud modernization strategy, and AI roadmap.',
    duration: 60,
    category: 'Consulting',
    price: 350,
    isActive: true,
  },
  {
    name: 'Therapeutic Deep Tissue Massage',
    description: 'Targeted muscle tension relief, postural realignment, and muscle recovery therapy.',
    duration: 60,
    category: 'Wellness',
    price: 150,
    isActive: true,
  },
  {
    name: 'Financial Advisory & Wealth Planning',
    description: 'Personalized portfolio diversification, tax optimization, and retirement planning session.',
    duration: 45,
    category: 'Finance',
    price: 250,
    isActive: true,
  },
];

export const seedStaffData = [
  {
    name: 'Dr. Evelyn Vance',
    email: 'staff.vance@schedulo.com',
    phone: '+1-555-0101',
    department: 'Healthcare & Medicine',
    specialization: 'Internal Medicine & Cardiology',
    bio: 'Board-certified physician with over 12 years of experience in preventive health and cardiology.',
    profileImage: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=250',
    workingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    workingHours: { start: '09:00', end: '17:00' },
    isActive: true,
  },
  {
    name: 'Marcus Holloway',
    email: 'staff.marcus@schedulo.com',
    phone: '+1-555-0102',
    department: 'Technology Consulting',
    specialization: 'Cloud Infrastructure & Enterprise AI',
    bio: 'Senior Technology Consultant helping enterprise leaders implement scalable infrastructure.',
    profileImage: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=250',
    workingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    workingHours: { start: '09:00', end: '17:00' },
    isActive: true,
  },
  {
    name: 'Sophia Chen',
    email: 'staff.sophia@schedulo.com',
    phone: '+1-555-0103',
    department: 'Wellness & Rehabilitation',
    specialization: 'Physiotherapy & Sports Wellness',
    bio: 'Licensed wellness specialist focused on athletic injury rehabilitation and holistic therapy.',
    profileImage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250',
    workingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    workingHours: { start: '10:00', end: '18:00' },
    isActive: true,
  },
];
